script: 
  - npm test
  - npm run e2e
language: node_js
node_js:
  - "0.10"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 3 # give server time to start
script:
  - npm test
  - npm e2e